apiVersion: apps/v1
kind: Deployment
metadata: 
  name: example-deploy
  labels: 
    app: example-app
  annotation: 
spec: 
  selector:
    matchLabels:
      app: example-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: aimvector/golang:1.0.0
        imagePullPolicy: Always
        ports:
        
